import { HttpException, HttpStatus } from '@nestjs/common';

export enum ApplicationErrorCode {
  AUTH_REQUIRED = 'AUTH_REQUIRED',
  FORBIDDEN = 'FORBIDDEN',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  INVALID_STATE_TRANSITION = 'INVALID_STATE_TRANSITION',
  DRIVER_NOT_READY = 'DRIVER_NOT_READY',
  DRIVER_OFFLINE = 'DRIVER_OFFLINE',
  DRIVER_BUSY = 'DRIVER_BUSY',
  VEHICLE_MISMATCH = 'VEHICLE_MISMATCH',
  OFFER_EXPIRED = 'OFFER_EXPIRED',
  OFFER_NOT_RECIPIENT = 'OFFER_NOT_RECIPIENT',
  RIDE_ALREADY_TAKEN = 'RIDE_ALREADY_TAKEN',
  INVALID_RIDE_PIN = 'INVALID_RIDE_PIN',
  PIN_ATTEMPTS_EXCEEDED = 'PIN_ATTEMPTS_EXCEEDED',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  PAYMENT_REQUIRED = 'PAYMENT_REQUIRED',
  PAYMENT_PROVIDER_UNAVAILABLE = 'PAYMENT_PROVIDER_UNAVAILABLE',
  INVALID_CALLBACK_SIGNATURE = 'INVALID_CALLBACK_SIGNATURE',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  WITHDRAWAL_ALREADY_PROCESSING = 'WITHDRAWAL_ALREADY_PROCESSING',
  RATE_LIMITED = 'RATE_LIMITED',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}

export class ApplicationError extends HttpException {
  constructor(
    status: HttpStatus | number,
    code: ApplicationErrorCode,
    message: string | string[],
    details: Record<string, unknown> = {},
  ) {
    super({ statusCode: status, code, message, ...details }, status);
  }
}
